apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order_pub_sub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers # Required. Kafka broker connection setting
    value: "kafka:9092"
  - name: authType # Required.
    value: "none"
  - name: authRequired
    value: "false"
  - name: disableTls
    value: "true"
scopes:
  - orderprocessing
  - checkout

# apiVersion: dapr.io/v1alpha1 # redis working
# kind: Component
# metadata:
#   name: order_pub_sub
# spec:
#   type: pubsub.redis
#   version: v1
#   metadata:
#   - name: redisHost
#     value: redis:6379
#   - name: redisPassword
#     value: ""
# scopes:
#   - orderprocessing
#   - checkout


# apiVersion: dapr.io/v1alpha1 # rabbitmq working
# kind: Component
# metadata:
#   name: order_pub_sub
# spec:
#   type: pubsub.rabbitmq
#   version: v1
#   metadata:
#   - name: host
#     value: "amqp://rabbitmq:5672"
#   - name: durable
#     value: "false"
#   - name: deletedWhenUnused
#     value: "false"
#   - name: autoAck
#     value: "false"
#   - name: reconnectWait
#     value: "0"
#   - name: concurrency
#     value: parallel
# scopes:
#   - orderprocessing
#   - checkout